spring:
  application:
    name: gtech-app
  datasource:
    url: jdbc:h2:mem:testdb   # In-memory database
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true           # Enables H2 web console at /h2-console
      path: /h2-console
